[package]
name = "h2-sql"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
h2-types = { path = "../h2-types" }
h2-mvstore = { path = "../h2-mvstore" }
h2-graph = { path = "../h2-graph" }
sqlparser = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
parking_lot = { workspace = true }
rust_decimal = { workspace = true }
chrono = { workspace = true }
regex = { workspace = true }
uuid = { workspace = true }
arrow = { workspace = true }
parquet = { workspace = true }
bincode = "1.3"
tracing = { workspace = true }

