[package]
name = "h2"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
h2-types = { path = "../h2-types" }
h2-mvstore = { path = "../h2-mvstore" }
h2-sql = { path = "../h2-sql" }
h2-server = { path = "../h2-server", optional = true }
h2-graph = { path = "../h2-graph", optional = true }
h2-bolt = { path = "../h2-bolt", optional = true }
tokio = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }


[features]
default = ["server", "bolt", "async"]
server = ["dep:h2-server"]
bolt = ["dep:h2-bolt", "dep:h2-graph"]
async = []

[dev-dependencies]
tempfile = "3.14"
tokio = { workspace = true, features = ["full"] }
rust_decimal = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
arrow = { workspace = true }
